language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"
install: 
    - "pip install --upgrade setuptools"
    - "pip install coveralls"
    - "pip install -e .[deps,sh]"
script: 
    python setup.py test
after_success: 
    coveralls
