language: python
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    # - TOXENV=py36

install:
    - pip install tox coveralls

script:
    - tox

after_success:
    coveralls
